In [4]:
%matplotlib inline

In [22]:
import warnings
warnings.filterwarnings('ignore')

In [23]:
import sqlite3
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import spearmanr
from pandas.plotting import scatter_matrix
from sklearn import preprocessing
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import OneClassSVM
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score

In [6]:
import pickle

with open('Pickle/y1.pickle', 'rb') as f:
    y1 = pickle.load(f)
    
with open('Pickle/y2.pickle', 'rb') as f:
    y2 = pickle.load(f)

X = pd.read_pickle('Pickle/X1_ML.pickle')

Xs = pd.read_pickle('Pickle/X1_Scaled_ML.pickle')

In [10]:
X2 = pd.read_pickle('Pickle/X2_ML.pickle')

X2s = pd.read_pickle('Pickle/X2_Scaled_ML.pickle')

In [17]:
X2_test = pd.read_pickle('Pickle/X2_Test.pickle')

In [31]:
X2_test.head()

BlockGroupFreq  temperature  tod_Early Morning  tod_Morning  tod_Afternoon  \
0       -0.890226    -0.904051           4.795959    -0.524598      -0.718111   
1       -0.890226    -0.174531          -0.208509    -0.524598      -0.718111   
2       -0.890226    -1.571122          -0.208509    -0.524598      -0.718111   
3       -0.890226    -0.936979          -0.208509    -0.524598       1.392542   
4       -0.890226    -0.686615          -0.208509    -0.524598       1.392542   

   tod_Evening  tod_Night  tod_Midnight  uv_index  
0    -0.466254  -0.400282     -0.306005 -0.720425  
1    -0.466254   2.498240     -0.306005 -0.720425  
2     2.144754  -0.400282     -0.306005 -0.720425  
3    -0.466254  -0.400282     -0.306005  0.999489  
4    -0.466254  -0.400282     -0.306005 -0.290447

In [32]:
X2_testd = X2_test.drop(columns = ['uv_index'])

In [17]:
y1[0]

array([80.64516129])

In [12]:
y2.head()

0    Med
1    Med
2    Med
3    Med
4    Med
Name: CrimeCategory, dtype: object

In [6]:
X.head()

cloud_cover  dew_point  humidity  percip_intensity  percip_probability  \
0         0.34      27.77      0.52            0.0000                0.00   
1         0.98      55.38      0.93            0.1323                0.99   
2         0.91      18.64      0.56            0.0000                0.00   
3         0.00      28.66      0.55            0.0053                0.22   
4         0.72      27.55      0.44            0.0000                0.00   

   pressure  temperature  uv_index  visibility  wind_bearing  ...  bgCat_1.0  \
0   1031.65        44.43       0.0        5.77         330.0  ...          0   
1    996.10        57.28       0.0        3.57         110.0  ...          0   
2   1015.17        32.68       0.0        6.67         161.0  ...          0   
3   1016.32        43.85       4.0        6.54         305.0  ...          0   
4   1020.88        48.26       1.0        6.40         339.0  ...          0   

   bgCat_2.0  bgCat_3.0  bgCat_4.0  bgCat_5.0  Year_2013  Year_2014  \
0          0          0          0          0          1          0   
1          0          0          0          0          1          0   
2          0          0          0          0          1          0   
3          0          0          0          0          1          0   
4          0          0          0          0          1          0   

   Year_2015  Year_2016  Year_2017  
0          0          0          0  
1          0          0          0  
2          0          0          0  
3          0          0          0  
4          0          0          0  

[5 rows x 22 columns]

In [7]:
Xs.head()

cloud_cover  dew_point  humidity  percip_intensity  percip_probability  \
0    -0.358144  -1.051885 -0.718503         -0.182472           -0.327636   
1     1.401721   0.412097  1.498391          9.104426            4.696037   
2     1.209236  -1.535991 -0.502221         -0.182472           -0.327636   
3    -1.293072  -1.004694 -0.556291          0.189566            0.788736   
4     0.686776  -1.063550 -1.151068         -0.182472           -0.327636   

   pressure  temperature  uv_index  visibility  wind_bearing  ...  bgCat_1.0  \
0  2.024517    -0.904051 -0.720425   -1.283707      1.280647  ...  -0.450896   
1 -3.048742    -0.174531 -0.720425   -2.804589     -0.941366  ...  -0.450896   
2 -0.327306    -1.571122 -0.720425   -0.661528     -0.426263  ...  -0.450896   
3 -0.163192    -0.936979  0.999489   -0.751398      1.028146  ...  -0.450896   
4  0.487555    -0.686615 -0.290447   -0.848182      1.371548  ...  -0.450896   

   bgCat_2.0  bgCat_3.0  bgCat_4.0  bgCat_5.0  Year_2013  Year_2014  \
0  -0.514676  -0.387771  -0.423279   -0.58038   1.982382  -0.522071   
1  -0.514676  -0.387771  -0.423279   -0.58038   1.982382  -0.522071   
2  -0.514676  -0.387771  -0.423279   -0.58038   1.982382  -0.522071   
3  -0.514676  -0.387771  -0.423279   -0.58038   1.982382  -0.522071   
4  -0.514676  -0.387771  -0.423279   -0.58038   1.982382  -0.522071   

   Year_2015  Year_2016  Year_2017  
0  -0.506985  -0.500438  -0.465687  
1  -0.506985  -0.500438  -0.465687  
2  -0.506985  -0.500438  -0.465687  
3  -0.506985  -0.500438  -0.465687  
4  -0.506985  -0.500438  -0.465687  

[5 rows x 22 columns]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X2_test, y2, test_size=0.3)

In [18]:
model = KNeighborsClassifier(3)
model.fit(X_train, y_train)

expected = y_test
predicted = model.predict(X_test)

print('K Neighbor Classifier')
print('Accuracy score = %0.3f' % accuracy_score(expected, predicted))

K Neighbor Classifier
Accuracy score = 0.456


In [34]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

expected = y_test
predicted = model.predict(X_test)


print('Random Forest model')
print('Accuracy score = %0.3f' % accuracy_score(expected, predicted))


# Compute and return F1 (harmonic mean of precision and recall)
print("{}: {}".format(model.__class__.__name__, f1_score(expected, predicted, average = 'micro')))
print(confusion_matrix(expected, predicted))

Random Forest model
Accuracy score = 0.633
RandomForestClassifier: 0.6334055017829853
[[ 5658   207  1596  1955]
 [  197  6095  1541   624]
 [ 1453  1633 12300  2378]
 [ 2147   729  2811  5788]]


In [35]:
X_train, X_test, y_train, y_test = train_test_split(X2_testd, y2, test_size=0.3)

model = RandomForestClassifier()
model.fit(X_train, y_train)

expected = y_test
predicted = model.predict(X_test)


print('Random Forest model')
print('Accuracy score = %0.3f' % accuracy_score(expected, predicted))


# Compute and return F1 (harmonic mean of precision and recall)
print("{}: {}".format(model.__class__.__name__, f1_score(expected, predicted, average = 'micro')))
print(confusion_matrix(expected, predicted))

Random Forest model
Accuracy score = 0.643
RandomForestClassifier: 0.6432968245882154
[[ 5839   180  1449  1956]
 [  215  6187  1575   609]
 [ 1374  1476 12387  2252]
 [ 2176   737  2806  5894]]


In [21]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(max_depth=5)
model.fit(X_train, y_train)

expected = y_test
predicted = model.predict(X_test)


print('Random Forest model')
print('Accuracy score = %0.3f' % accuracy_score(expected, predicted))
confusion_matrix(expected, predicted)

Random Forest model
Accuracy score = 0.476


array([[ 2120,  1480,  3218,  2594],
       [   29,  5395,  2526,   609],
       [  499,  3446, 10704,  3056],
       [  995,   534,  5711,  4196]])

In [ ]:
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF

X_train, X_test, y_train, y_test = train_test_split(Xs, y2, test_size=10000, train_size=10000)

model = GaussianProcessClassifier(1.0 * RBF(1.0))
model.fit(X_train, y_train)

expected = y_test
predicted = model.predict(X_test)

print('K Neighbor Classifier')
print('Accuracy score = %0.3f' % accuracy_score(expected, predicted))

In [8]:
X_train, X_test, y_train, y_test = train_test_split(Xs, y1, test_size=10000, train_size=10000)

model = OneClassSVM()
model.fit(X_train, y_train)

expected = y_test
predicted = model.predict(X_test)

print('OneClassSVM')
print('Mean squared error = %0.3f' % mse(expected, predicted))
print('R2 score = %0.3f' % r2_score(expected, predicted))

/Users/DanSchorer/anaconda/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


OneClassSVM
Mean squared error = 9149.384
R2 score = -2.833
